imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        admin_tag_version:        "v0.0.1"
        main_brand_title: "%project_web_title%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%path_java%"
    node:           "%path_node%"
    filters:
        cssrewrite: ~
        less:
            node:       "%path_node%"
            node_paths: [ "%path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/frontend.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"

# Sonata
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~
        sonata.block.service.text:      ~
        admin.block.screener:

# Admin
sonata_admin:
    title: "%project_web_title%"
#    title_logo: "/bundles/app/img/logo-espai-kowo-backend.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    templates:
        layout: "::Admin/layout.html.twig"
#        show:   "::Admin/show.html.twig"
    dashboard:
        groups:
            SuperSector:
                icon: "<i class='fa fa-microphone' aria-hidden='true'></i>"
            Sector:
                icon: "<i class='fa fa-microphone' aria-hidden='true'></i>"
            Stock:
                icon: "<i class='fa fa-microphone' aria-hidden='true'></i>"
            Screener:
                icon: "<i class='fa fa-microphone' aria-hidden='true'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">Stock Screener</h1>
            -
                position: left
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ SuperSector, Sector, Stock, Screener ]
            -
                position: right
                type: admin.block.screener
                class: col-md-6

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:       "%locale%"
    orm:
        default:
            softdeleteable: false
            timestampable:  true
            sluggable:      false
            translatable:   false
            sortable:       false
            tree:           false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
