services:
# Sonata Admin
    admin.supersector:
        class: AppBundle\Admin\SuperSectorAdmin
        arguments: [ ~ , AppBundle\Entity\SuperSector , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Super Sector", group: "SuperSector" }
    admin.sector:
        class: AppBundle\Admin\SectorAdmin
        arguments: [ ~ , AppBundle\Entity\Sector , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Sector", group: "Sector" }
    admin.stock:
        class: AppBundle\Admin\StockAdmin
        arguments: [ ~ , AppBundle\Entity\Stock , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Stock", group: "Stock" }
    admin.sectorscreener:
        class: AppBundle\Admin\SectorscreenerAdmin
        arguments: [ ~ , AppBundle\Entity\Sectorscreener, AppBundle:Admin\SectorscreenerAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Sector Screener", group: "Screener" }
    admin.stockscreener:
        class: AppBundle\Admin\StockscreenerAdmin
        arguments: [ ~ , AppBundle\Entity\Stockscreener, AppBundle:Admin\StockscreenerAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Stock Screener", group: "Screener" }
# Sonata Blocks
    admin.block.screener:
        class: AppBundle\Admin\Block\MyBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.messages", "@templating" ]
