services:
# Sonata Admin
    admin.superSector:
        class: AppBundle\Admin\SuperSector
        arguments: [ ~ , AppBundle\Entity\SuperSector, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Super Sector", group: "Screener" }
